<?php

namespace Database\Seeders;

use App\Models\BacklinkOrder;
use App\Models\User;
use Illuminate\Database\Seeder;

class BacklinkOrderSeeder extends Seeder
{
    /**
     * Seeds backlink order rows using the initial tracking table data.
     * Computed fields (days_left, projected_health) are not stored —
     * they are calculated at query time by the API.
     */
    public function run(): void
    {
        // Resolve staff users by email so we can set link_builder_user_id.
        $staff_map = User::whereIn('email', [
            'kaitlin.anderson@97thfloor.com',
            'amanda.hevener@97thfloor.com',
            'lauren.barney@97thfloor.com',
            'krista.bennett@97thfloor.com',
        ])->pluck('id', 'email');

        $anderson_id = $staff_map['kaitlin.anderson@97thfloor.com'] ?? null;
        $hevener_id  = $staff_map['amanda.hevener@97thfloor.com']  ?? null;
        $barney_id   = $staff_map['lauren.barney@97thfloor.com']   ?? null;

        $rows = [
            [
                'order_id'                  => 'BL-19319',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'PolicySweet',
                'keyword'                   => 'Business Owners Policy',
                'landing_page'              => 'https://www.policysweet.com/business-owners-policy',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $anderson_id,
                'link_builder'              => '2. Anderson, Kaitlin',
                'pen_name'                  => 'Rebecca',
                'partnership'               => 'walkermagazine.com',
                'article_title'             => '',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://walkermagazine.com/the-benefits',
                'live_link_date'            => '12/12/2024',
                'dr_lbs'                    => '37',
                'posting_fee_lbs'           => '$25',
                'current_traffic'           => '171',
                'dr_formula'                => '37',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/13/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19320',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'PolicySweet',
                'keyword'                   => 'Business Owners Policy',
                'landing_page'              => 'https://www.policysweet.com/business-owners-policy',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $anderson_id,
                'link_builder'              => '2. Anderson, Kaitlin',
                'pen_name'                  => 'ms link builder',
                'partnership'               => 'celebsliving.com',
                'article_title'             => '',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://celebsliving.com/how-business-ow',
                'live_link_date'            => '12/11/2024',
                'dr_lbs'                    => '36',
                'posting_fee_lbs'           => '$18',
                'current_traffic'           => '131',
                'dr_formula'                => '36',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/12/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19321',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'PolicySweet',
                'keyword'                   => 'Business Owners Policy',
                'landing_page'              => 'https://www.policysweet.com/business-owners-policy',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $anderson_id,
                'link_builder'              => '2. Anderson, Kaitlin',
                'pen_name'                  => 'ms link builder',
                'partnership'               => 'vefeast.com',
                'article_title'             => '',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://vefeast.com/how-business-owner',
                'live_link_date'            => '12/17/2024',
                'dr_lbs'                    => '42',
                'posting_fee_lbs'           => '$17',
                'current_traffic'           => '467',
                'dr_formula'                => '42',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/17/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19322',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'PolicySweet',
                'keyword'                   => 'Business Owners Policy',
                'landing_page'              => 'https://www.policysweet.com/business-owners-policy',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $anderson_id,
                'link_builder'              => '2. Anderson, Kaitlin',
                'pen_name'                  => 'ms link builder',
                'partnership'               => 'wordstreetjournal.com',
                'article_title'             => '',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://vatonlinecalculator.co.uk/the-impo',
                'live_link_date'            => '12/11/2024',
                'dr_lbs'                    => '40',
                'posting_fee_lbs'           => '$22',
                'current_traffic'           => '6729',
                'dr_formula'                => '40',
                'current_poc'               => 'Muhammad',
                'current_price'             => '$20',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/11/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19323',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'PolicySweet',
                'keyword'                   => 'Business Owners Policy',
                'landing_page'              => 'https://www.policysweet.com/business-owners-policy',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $hevener_id,
                'link_builder'              => '2. Hevener, Amanda',
                'pen_name'                  => 'Areeba',
                'partnership'               => 'forbeszine.com',
                'article_title'             => 'The Importance of Business Insurance',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://forbeszine.com/the-importance-of',
                'live_link_date'            => '12/12/2024',
                'dr_lbs'                    => '38',
                'posting_fee_lbs'           => '$25',
                'current_traffic'           => '0',
                'dr_formula'                => '38',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/13/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19324',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'PolicySweet',
                'keyword'                   => 'Business Owners Policy',
                'landing_page'              => 'https://www.policysweet.com/business-owners-policy',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $hevener_id,
                'link_builder'              => '2. Hevener, Amanda',
                'pen_name'                  => 'Areeba',
                'partnership'               => 'tribuneindian.com',
                'article_title'             => 'Understanding the Different Types of Business Insurance',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://www.tribuneindian.com/understan',
                'live_link_date'            => '12/12/2024',
                'dr_lbs'                    => '37',
                'posting_fee_lbs'           => '$25',
                'current_traffic'           => '1',
                'dr_formula'                => '37',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/13/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19325',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'PolicySweet',
                'keyword'                   => 'Business Owners Policy',
                'landing_page'              => 'https://www.policysweet.com/business-owners-policy',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $hevener_id,
                'link_builder'              => '2. Hevener, Amanda',
                'pen_name'                  => 'Arijit',
                'partnership'               => 'captionsunleashed.com',
                'article_title'             => 'How to Choose Business Insurance',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://captionsunleashed.com/how-to-ch',
                'live_link_date'            => '12/3/2024',
                'dr_lbs'                    => '40',
                'posting_fee_lbs'           => '$20',
                'current_traffic'           => '1056',
                'dr_formula'                => '40',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/4/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19326',
                'team_specific_link_id'     => 'AMA-157',
                'link_type'                 => 'DA 30+ External',
                'client'                    => 'Amagi',
                'keyword'                   => 'Amagi podcast',
                'landing_page'              => 'https://www.amagi.com/podcasts',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $anderson_id,
                'link_builder'              => '2. Anderson, Kaitlin',
                'pen_name'                  => 'Rebecca',
                'partnership'               => 'coopermagazine.co.uk',
                'article_title'             => '',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://coopermagazine.co.uk/brands-anc',
                'live_link_date'            => '12/12/2024',
                'dr_lbs'                    => '38',
                'posting_fee_lbs'           => '$25',
                'current_traffic'           => '2088',
                'dr_formula'                => '38',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/13/2024',
                'final_price'               => '$250.0',
            ],
            [
                'order_id'                  => 'BL-19327',
                'team_specific_link_id'     => 'AMA-163',
                'link_type'                 => 'DA 40+ External',
                'client'                    => 'Amagi',
                'keyword'                   => 'how to launch a fast channel',
                'landing_page'              => 'https://www.amagi.com/blog/how-to-launch-fast-channel',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $anderson_id,
                'link_builder'              => '2. Anderson, Kaitlin',
                'pen_name'                  => 'hammad',
                'partnership'               => 'starmusiqweb.com',
                'article_title'             => '',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://starmusiqweb.com/a-guide-for-lau',
                'live_link_date'            => '12/12/2024',
                'dr_lbs'                    => '60',
                'posting_fee_lbs'           => '$20',
                'current_traffic'           => '3207',
                'dr_formula'                => '60',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/13/2024',
                'final_price'               => '$300.0',
            ],
            [
                'order_id'                  => 'BL-19328',
                'team_specific_link_id'     => 'AMA-168',
                'link_type'                 => 'DA 50+ External',
                'client'                    => 'Amagi',
                'keyword'                   => 'how to launch a fast channel',
                'landing_page'              => 'https://www.amagi.com/blog/how-to-launch-fast-channel',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $anderson_id,
                'link_builder'              => '2. Anderson, Kaitlin',
                'pen_name'                  => 'Christina',
                'partnership'               => 'anationofmoms.com',
                'article_title'             => '',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://anationofmoms.com/2024/12/free-',
                'live_link_date'            => '12/17/2024',
                'dr_lbs'                    => '67',
                'posting_fee_lbs'           => '$65',
                'current_traffic'           => '1975',
                'dr_formula'                => '67',
                'current_poc'               => 'Arslan',
                'current_price'             => '$25',
                'lb_tl_approval'            => 'Amanda',
                'approval_date'             => '12/17/2024',
                'final_price'               => '$375.0',
            ],
            [
                'order_id'                  => 'BL-19329',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'cybersecurity marketing agency',
                'landing_page'              => 'https://97thfloor.com/industries/cybersecurity/',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'David Wirt',
                'partnership'               => 'letmagazine.com',
                'article_title'             => 'Strategies For Protecting Sensitive Information',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://www.letmagazine.com/strategies-',
                'live_link_date'            => '12/18/2024',
                'dr_lbs'                    => '42',
                'posting_fee_lbs'           => '$25',
                'current_traffic'           => '33',
                'dr_formula'                => '42',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '1/4/2025',
                'final_price'               => '$55.0',
            ],
            [
                'order_id'                  => 'BL-19330',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 40+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'cybersecurity marketing agency',
                'landing_page'              => 'https://97thfloor.com/industries/cybersecurity/',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'Bobby Jesse',
                'partnership'               => 'explorethings.org',
                'article_title'             => 'Simple Tips for Effective Outsourcing',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://explorethings.org/tips-for-effective',
                'live_link_date'            => '12/20/2024',
                'dr_lbs'                    => '45',
                'posting_fee_lbs'           => '$50',
                'current_traffic'           => '0',
                'dr_formula'                => '45',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '1/2/2025',
                'final_price'               => '$80.0',
            ],
            [
                'order_id'                  => 'BL-19331',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'digital marketing services',
                'landing_page'              => 'https://97thfloor.com/services/',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'Hammad',
                'partnership'               => 'usawire.com',
                'article_title'             => 'Building a Digital Foundation for Your Business',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://usawire.com/building-a-digital-fo',
                'live_link_date'            => '12/17/2024',
                'dr_lbs'                    => '55',
                'posting_fee_lbs'           => '$12',
                'current_traffic'           => '5203',
                'dr_formula'                => '55',
                'current_poc'               => 'Muhammad',
                'current_price'             => '$15',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '1/2/2025',
                'final_price'               => '$55.0',
            ],
            [
                'order_id'                  => 'BL-19332',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'digital marketing services',
                'landing_page'              => 'https://97thfloor.com/services/',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'Hammad',
                'partnership'               => 'wistomagazine.co.uk',
                'article_title'             => 'Becoming a Household Name in Business',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://wistomagazine.co.uk/becoming-a',
                'live_link_date'            => '12/10/2024',
                'dr_lbs'                    => '37',
                'posting_fee_lbs'           => '$12',
                'current_traffic'           => '0',
                'dr_formula'                => '37',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '12/16/2024',
                'final_price'               => '$55.0',
            ],
            [
                'order_id'                  => 'BL-19333',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'saas digital marketing agency',
                'landing_page'              => 'https://97thfloor.com/industries/saas/',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'Hammad',
                'partnership'               => 'picnob.uk',
                'article_title'             => 'The Role of Software in Modern Business',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://picnob.uk/2024/12/10/the-role-of-',
                'live_link_date'            => '12/10/2024',
                'dr_lbs'                    => '36',
                'posting_fee_lbs'           => '$15',
                'current_traffic'           => '0',
                'dr_formula'                => '36',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '12/16/2024',
                'final_price'               => '$55.0',
            ],
            [
                'order_id'                  => 'BL-19334',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'saas digital marketing agency',
                'landing_page'              => 'https://97thfloor.com/industries/saas/',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'Hammad',
                'partnership'               => 'kidzmommy.com',
                'article_title'             => 'Marketing Trends and Developments',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://kidzmommy.com/marketing-trends-',
                'live_link_date'            => '12/9/2024',
                'dr_lbs'                    => '42',
                'posting_fee_lbs'           => '$20',
                'current_traffic'           => '688',
                'dr_formula'                => '42',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '12/16/2024',
                'final_price'               => '$55.0',
            ],
            [
                'order_id'                  => 'BL-19335',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 30+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'saas digital marketing agency',
                'landing_page'              => 'https://97thfloor.com/industries/saas/',
                'exact_match'               => 'No',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'Hammad',
                'partnership'               => 'scrollblogs.co.uk',
                'article_title'             => 'What You Should Know About Working Remotely',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://scrollblogs.co.uk/what-you-should',
                'live_link_date'            => '12/11/2024',
                'dr_lbs'                    => '38',
                'posting_fee_lbs'           => '$15',
                'current_traffic'           => '0',
                'dr_formula'                => '38',
                'current_poc'               => 'SITE REMOVED',
                'current_price'             => 'SITE REMOVED',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '12/16/2024',
                'final_price'               => '$55.0',
            ],
            [
                'order_id'                  => 'BL-19336',
                'team_specific_link_id'     => '',
                'link_type'                 => 'DA 40+ Internal',
                'client'                    => '97th Floor',
                'keyword'                   => 'saas digital marketing agency',
                'landing_page'              => 'https://97thfloor.com/industries/saas/',
                'exact_match'               => 'Yes',
                'notes'                     => '',
                'request_date'              => '12/2/2024',
                'estimated_delivery_date'   => '1/1/2025',
                'estimated_turnaround_days' => 30,
                'link_builder_user_id'      => $barney_id,
                'link_builder'              => '1. Barney, Lauren',
                'pen_name'                  => 'Arslan Khan',
                'partnership'               => 'educba.com',
                'article_title'             => 'Reaching Younger Consumers with Your Marketing',
                'article'                   => 'https://docs.google.com/d',
                'status'                    => 'Live',
                'live_link'                 => 'https://www.educba.com/reaching-young-',
                'live_link_date'            => '12/27/2024',
                'dr_lbs'                    => '58',
                'posting_fee_lbs'           => '$50',
                'current_traffic'           => '131486',
                'dr_formula'                => '58',
                'current_poc'               => 'Muhammad',
                'current_price'             => '$40',
                'lb_tl_approval'            => 'Krista',
                'approval_date'             => '1/2/2025',
                'final_price'               => '$80.0',
            ],
        ];

        foreach ($rows as $row) {
            BacklinkOrder::updateOrCreate(
                ['order_id' => $row['order_id']],
                $row
            );
        }
    }
}
