<?php

namespace Database\Seeders;

use App\Models\NewsPlacement;
use Illuminate\Database\Seeder;

class NewsPlacementSeeder extends Seeder
{
    /**
     * Seeds news placement rows from the initial Premium News Placements database.
     * Only rows with a domain value are included.
     * Safe to run multiple times — uses updateOrCreate keyed on domain.
     */
    public function run(): void
    {
        $rows = [
            [
                'domain'              => 'apnews.com',
                'dr'                  => '92',
                'traffic'             => '5696617',
                'category'            => 'General, Business',
                'price'               => '$72',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$65',
                'poc_1'               => 'Muhammad',
                'price_2'             => '$140',
                'poc_2'               => 'Arslan',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '245551',
            ],
            [
                'domain'              => 'asiatimes.com',
                'dr'                  => '76',
                'traffic'             => '20873',
                'category'            => 'General',
                'price'               => '$121',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$110',
                'poc_1'               => 'Hamza',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '19956',
            ],
            [
                'domain'              => 'barchart.com',
                'dr'                  => '80',
                'traffic'             => '2015764',
                'category'            => 'Finance',
                'price'               => '$55',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => '',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$40',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '23561',
            ],
            [
                'domain'              => 'benzinga.com',
                'dr'                  => '86',
                'traffic'             => '685438',
                'category'            => 'Business, Finance',
                'price'               => '$88',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$80',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '55144',
            ],
            [
                'domain'              => 'businessinsider.com',
                'dr'                  => '92',
                'traffic'             => '7469837',
                'category'            => 'Business',
                'price'               => '$363',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$330',
                'poc_1'               => 'Float Team',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '404721',
            ],
            [
                'domain'              => 'digitaljournal.com',
                'dr'                  => '86',
                'traffic'             => '24645',
                'category'            => 'Tech, Business, News',
                'price'               => '$55',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$30',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '56449',
            ],
            [
                'domain'              => 'entrepreneur.com',
                'dr'                  => '91',
                'traffic'             => '547377',
                'category'            => 'Business',
                'price'               => '$1,595',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$1,450',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => '',
                'within_budget'       => 'No',
                'ref_domains'         => '147529',
            ],
            [
                'domain'              => 'finance.yahoo.com',
                'dr'                  => '94',
                'traffic'             => '97234251',
                'category'            => 'Finance',
                'price'               => '$176',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$160',
                'poc_1'               => 'Muhammad',
                'price_2'             => '$200',
                'poc_2'               => 'Arslan',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '260281',
            ],
            [
                'domain'              => 'forbes.com',
                'dr'                  => '94',
                'traffic'             => '19594122',
                'category'            => 'Business',
                'price'               => '$5,720',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => '',
                'indexable'           => '',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$5,200',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'No',
                'ref_domains'         => '813549',
            ],
            [
                'domain'              => 'investing.com',
                'dr'                  => '88',
                'traffic'             => '82310405',
                'category'            => 'Finance',
                'price'               => '$253',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$230',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => '',
                'within_budget'       => 'Yes',
                'ref_domains'         => '79632',
            ],
            [
                'domain'              => 'manilatimes.net',
                'dr'                  => '79',
                'traffic'             => '166401',
                'category'            => 'News, General',
                'price'               => '$149',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$135',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '21045',
            ],
            [
                'domain'              => 'markets.businessinsider.com',
                'dr'                  => '92',
                'traffic'             => '2782764',
                'category'            => 'Finance, Business',
                'price'               => '$121',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$110',
                'poc_1'               => 'Muhammad',
                'price_2'             => '$200',
                'poc_2'               => 'Arslan',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '59442',
            ],
            [
                'domain'              => 'msn.com',
                'dr'                  => '92',
                'traffic'             => '27072706',
                'category'            => 'General, News',
                'price'               => '$880',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => '',
                'indexable'           => '',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$800',
                'poc_1'               => 'Sienna',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'No',
                'ref_domains'         => '322042',
            ],
            [
                'domain'              => 'outlookindia.com',
                'dr'                  => '87',
                'traffic'             => '2269980',
                'category'            => 'General',
                'price'               => '$275',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$250',
                'poc_1'               => 'Donald',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '4',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '87319',
            ],
            [
                'domain'              => 'radaronline.com',
                'dr'                  => '78',
                'traffic'             => '265832',
                'category'            => 'Finance',
                'price'               => '$1,650',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$1,500',
                'poc_1'               => 'Float Team',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'No',
                'ref_domains'         => '28924',
            ],
            [
                'domain'              => 'theglobeandmail.com',
                'dr'                  => '90',
                'traffic'             => '3844289',
                'category'            => 'News, General',
                'price'               => '$83',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$75',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '112637',
            ],
            [
                'domain'              => 'thestreet.com',
                'dr'                  => '86',
                'traffic'             => '1553164',
                'category'            => 'Finance',
                'price'               => '$1,067',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => 'content can only be 800 words max',
                'price_1'             => '$970',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '3',
                'used_domain'         => '',
                'within_budget'       => 'No',
                'ref_domains'         => '57515',
            ],
            [
                'domain'              => 'usatoday.com',
                'dr'                  => '92',
                'traffic'             => '29789684',
                'category'            => 'News',
                'price'               => '$231',
                'types_of_content'    => 'Branded Article, Press Release',
                'do_follow_no_follow' => 'No-Follow',
                'indexable'           => 'No',
                'well_known_site'     => 'Yes - globally',
                'links_allowed'       => '',
                'additional_notes'    => 'says links will be no followed and article no index after a few days; working on negotiating so links will stay up and be dofollow',
                'price_1'             => '$210',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => 'Arslan, Anisa?',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '2',
                'used_domain'         => '',
                'within_budget'       => 'Yes',
                'ref_domains'         => '323493',
            ],
            [
                'domain'              => 'analyticsinsight.net',
                'dr'                  => '80',
                'traffic'             => '312122',
                'category'            => 'News',
                'price'               => '$83',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$75',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '21588',
            ],
            [
                'domain'              => 'businessabc.net',
                'dr'                  => '81',
                'traffic'             => '13276',
                'category'            => 'Business',
                'price'               => '$110',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$100',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '5220',
            ],
            [
                'domain'              => 'coda.io',
                'dr'                  => '83',
                'traffic'             => '148195',
                'category'            => 'Tech',
                'price'               => '$83',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$75',
                'poc_1'               => 'Hammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '15642',
            ],
            [
                'domain'              => 'cybersecuritynews.com',
                'dr'                  => '78',
                'traffic'             => '12257',
                'category'            => 'General',
                'price'               => '$72',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$65',
                'poc_1'               => 'Hammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '8825',
            ],
            [
                'domain'              => 'devdiscourse.com',
                'dr'                  => '76',
                'traffic'             => '112843',
                'category'            => 'General',
                'price'               => '$715',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$650',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'No',
                'ref_domains'         => '11907',
            ],
            [
                'domain'              => 'financialcontent.com',
                'dr'                  => '81',
                'traffic'             => '468822',
                'category'            => 'Finance',
                'price'               => '$77',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => '',
                'indexable'           => '',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$70',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => '',
                'within_budget'       => 'Yes',
                'ref_domains'         => '41529',
            ],
            [
                'domain'              => 'housingwire.com',
                'dr'                  => '82',
                'traffic'             => '86213',
                'category'            => 'General',
                'price'               => '$105',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$95',
                'poc_1'               => 'Hamza',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '19814',
            ],
            [
                'domain'              => 'indiehackers.com',
                'dr'                  => '80',
                'traffic'             => '23484',
                'category'            => 'General',
                'price'               => '$77',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$70',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '18303',
            ],
            [
                'domain'              => 'inkl.com',
                'dr'                  => '71',
                'traffic'             => '93112',
                'category'            => 'General',
                'price'               => '$110',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$100',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '11366',
            ],
            [
                'domain'              => 'israelnationalnews.com',
                'dr'                  => '76',
                'traffic'             => '326407',
                'category'            => 'News',
                'price'               => '$132',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$120',
                'poc_1'               => 'Hamza',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '19192',
            ],
            [
                'domain'              => 'jingdaily.com',
                'dr'                  => '74',
                'traffic'             => '17290',
                'category'            => 'General',
                'price'               => '$121',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$110',
                'poc_1'               => 'Hamza',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '8554',
            ],
            [
                'domain'              => 'luxurylifestylemag.co.uk',
                'dr'                  => '71',
                'traffic'             => '10500',
                'category'            => 'General',
                'price'               => '$182',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '2',
                'additional_notes'    => '',
                'price_1'             => '$165',
                'poc_1'               => 'Muhammad',
                'price_2'             => '$240',
                'poc_2'               => 'Arslan',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '4877',
            ],
            [
                'domain'              => 'markets.financialcontent.com',
                'dr'                  => '81',
                'traffic'             => '189495',
                'category'            => 'Finance',
                'price'               => '$143',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$130',
                'poc_1'               => 'Donald',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '39757',
            ],
            [
                'domain'              => 'moderndiplomacy.eu',
                'dr'                  => '74',
                'traffic'             => '33694',
                'category'            => 'General',
                'price'               => '$154',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$140',
                'poc_1'               => 'Rank Castle',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '14315',
            ],
            [
                'domain'              => 'openpr.com',
                'dr'                  => '80',
                'traffic'             => '166869',
                'category'            => 'General',
                'price'               => '$55',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$45',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '27140',
            ],
            [
                'domain'              => 'streetinsider.com',
                'dr'                  => '79',
                'traffic'             => '28446',
                'category'            => 'Finance',
                'price'               => '$55',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => '',
                'indexable'           => '',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$35',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '22706',
            ],
            [
                'domain'              => 'techinasia.com',
                'dr'                  => '82',
                'traffic'             => '64025',
                'category'            => 'Tech',
                'price'               => '$660',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => '',
                'indexable'           => '',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$600',
                'poc_1'               => 'Bobby',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'No',
                'ref_domains'         => '34174',
            ],
            [
                'domain'              => 'technology.org',
                'dr'                  => '73',
                'traffic'             => '72122',
                'category'            => 'Tech',
                'price'               => '$182',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '2',
                'additional_notes'    => '',
                'price_1'             => '$165',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '8617',
            ],
            [
                'domain'              => 'walletinvestor.com',
                'dr'                  => '72',
                'traffic'             => '190933',
                'category'            => 'Finance',
                'price'               => '$363',
                'types_of_content'    => 'Press Release',
                'do_follow_no_follow' => '',
                'indexable'           => '',
                'well_known_site'     => 'Yes - industry wide',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$330',
                'poc_1'               => 'Bobby',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Exclusive Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '10561',
            ],
            [
                'domain'              => '99techpost.com',
                'dr'                  => '43',
                'traffic'             => '21491',
                'category'            => 'Business',
                'price'               => '$55',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$30',
                'poc_1'               => 'Bobby',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '1466',
            ],
            [
                'domain'              => 'aavot.co.uk',
                'dr'                  => '47',
                'traffic'             => '7183',
                'category'            => 'General, News, Business, Tech, Finance',
                'price'               => '$55',
                'types_of_content'    => 'Listicle, Branded Article, Press Release',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '2',
                'additional_notes'    => '',
                'price_1'             => '$15',
                'poc_1'               => 'Bobby',
                'price_2'             => '$35',
                'poc_2'               => 'Arslan',
                'tier'                => 'Core Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '564',
            ],
            [
                'domain'              => 'abcmoney.co.uk',
                'dr'                  => '60',
                'traffic'             => '1999',
                'category'            => 'General, Business',
                'price'               => '$138',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$125',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '4591',
            ],
            [
                'domain'              => 'abithelp.com',
                'dr'                  => '51',
                'traffic'             => '6535',
                'category'            => 'Tech',
                'price'               => '$92',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$84',
                'poc_1'               => 'Hammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '1276',
            ],
            [
                'domain'              => 'aboutbiography.com',
                'dr'                  => '30',
                'traffic'             => '9',
                'category'            => 'General',
                'price'               => '$55',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$30',
                'poc_1'               => 'Bobby',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Support Placement',
                'pbn_check'           => '1',
                'used_domain'         => '',
                'within_budget'       => 'Yes',
                'ref_domains'         => '835',
            ],
            [
                'domain'              => 'aboutlines.org',
                'dr'                  => '64',
                'traffic'             => '12630',
                'category'            => 'General',
                'price'               => '$55',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$35',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '2',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '37',
            ],
            [
                'domain'              => 'aboutmanchester.co.uk',
                'dr'                  => '58',
                'traffic'             => '1897',
                'category'            => 'General',
                'price'               => '$171',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '2',
                'additional_notes'    => '',
                'price_1'             => '$155',
                'poc_1'               => 'Muhammad',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => 'No',
                'ref_domains'         => '2179',
            ],
            [
                'domain'              => 'acadomi.org',
                'dr'                  => '52',
                'traffic'             => '66935',
                'category'            => 'General',
                'price'               => '$55',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$35',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '2',
                'used_domain'         => 'No',
                'within_budget'       => 'Yes',
                'ref_domains'         => '43',
            ],
            [
                'domain'              => 'accordshort.com',
                'dr'                  => '46',
                'traffic'             => '1761',
                'category'            => 'Tech',
                'price'               => '$110',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$100',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '1',
                'used_domain'         => 'Yes',
                'within_budget'       => 'Yes',
                'ref_domains'         => '1067',
            ],
            [
                'domain'              => 'acraftedpassion.com',
                'dr'                  => '34',
                'traffic'             => '1595',
                'category'            => 'General',
                'price'               => '$88',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$80',
                'poc_1'               => 'Arslan',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => '',
                'pbn_check'           => '2',
                'used_domain'         => 'No',
                'within_budget'       => '',
                'ref_domains'         => '675',
            ],
            [
                'domain'              => 'acrylicpedia.com',
                'dr'                  => '43',
                'traffic'             => '442',
                'category'            => 'General',
                'price'               => '$55',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$35',
                'poc_1'               => 'Misty',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => 'Core Placement',
                'pbn_check'           => '1',
                'used_domain'         => '',
                'within_budget'       => 'Yes',
                'ref_domains'         => '119',
            ],
            [
                'domain'              => 'actvid.co.uk',
                'dr'                  => '32',
                'traffic'             => '5698',
                'category'            => 'General',
                'price'               => '$77',
                'types_of_content'    => 'Branded Article',
                'do_follow_no_follow' => 'Do-Follow',
                'indexable'           => 'Yes',
                'well_known_site'     => '',
                'links_allowed'       => '',
                'additional_notes'    => '',
                'price_1'             => '$70',
                'poc_1'               => 'Rebecca',
                'price_2'             => '',
                'poc_2'               => '',
                'tier'                => '',
                'pbn_check'           => '1',
                'used_domain'         => 'No',
                'within_budget'       => '',
                'ref_domains'         => '386',
            ],
        ];

        foreach ($rows as $row) {
            NewsPlacement::updateOrCreate(
                ['domain' => $row['domain']],
                $row
            );
        }
    }
}
